services:

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlpw
      - MYSQL_USER=testuser
      - MYSQL_DATABASE=testdb
      - MYSQL_PASSWORD=123456
    ports:
      - 33067:3306


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080