version: '3'
services:

  mysql:
    image: mysql:5.7
    restart: always
    container_name: test-mysql-docker
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlpw
      - MYSQL_USER=infrastock
      - MYSQL_DATABASE=infrastock
      - MYSQL_PASSWORD=infrastock123
      - TZ=Europe/Warsaw
    ports:
      - 33067:3306
    volumes:
      - ./infrastock-db:/var/lib/mysql
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql

  api:
    image: czubakjakub/infrastock:v2.0.0
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://root:mysqlpw@test-mysql-docker:3306/infrastock?autoReconnect=true&useSSL=false&serverTimezone=Europe/Warsaw
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
    restart: always
    ports:
      - 9090:9090
    depends_on:
      - mysql